use_frameworks!

platform :ios, '13.0'

target 'DependencyPodTest_Example' do
  pod 'DependencyPodTest', :path => '../'

  target 'DependencyPodTest_Tests' do
    inherit! :search_paths

    
  end
end
